[package]
name = "daily_stack"
version = "0.1.0"
edition = "2024"

[workspace] # ✅ This tells Cargo not to look for a parent workspace

# 💁 Run `trunk serve --open` to launch the app 🚀

[profile.release]
opt-level = 'z'
codegen-units = 1
lto = true

[dependencies]
leptos_ui = "0.3"
tw_merge = { version = "0.1", features = ["variant"] }
leptos = { version = "0.8", features = ["csr"] }
leptos_router = { version = "0.8", features = ["nightly"] }
console_log = "1"
log = "0.4"
console_error_panic_hook = "0.1"
gloo-timers = { version = "0.3", features = ["futures"] }
web-sys = "0.3"

[dev-dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3"
leptos = { version = "0.8", features = ["ssr"] }
